version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: planrh_mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
      - ./seeds:/data/seed
    networks:
      - planrh_net

  backend:
    build:
      context: ./PlanRHAPI
      dockerfile: Dockerfile
    container_name: planrh_backend
    restart: always
    env_file:
      - ./PlanRHAPI/.env
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://planrh_mongo:27017
      - MONGO_DB=planRH
    depends_on:
      - mongo
    networks:
      - planrh_net
    expose:
      - "8000"

  frontend:
    build:
      context: ./PlanRhApp
      dockerfile: Dockerfile
    container_name: planrh_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - planrh_net
    depends_on:
      - backend

networks:
  planrh_net:
    driver: bridge
