version: "3.8"
services:
  backend:
    build:
      context: ./PlanRHAPI
      dockerfile: Dockerfile
    container_name: planrh_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./PlanRHAPI/.env
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - MONGO_DB=planRH
    networks:
      - planrh_net
    expose:
      - "8000"

  frontend:
    build:
      context: ./PlanRhApp
      dockerfile: Dockerfile
    container_name: planrh_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - planrh_net
    depends_on:
      - backend

networks:
  planrh_net:
    driver: bridge
